services:
  zookeeper-01:
    image: confluentinc/cp-zookeeper:7.5.3
    hostname: zookeeper-01
    container_name: zookeeper-01
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-01-data:/var/lib/zookeeper
    networks:
      - kafka-network

  kafka-broker-01:
    image: confluentinc/cp-kafka:7.5.3
    hostname: kafka-broker-01
    container_name: kafka-broker-01
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-01:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-01:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-network
    depends_on:
      - zookeeper-01
    volumes:
      - kafka-broker-01-data:/var/lib/kafka/data

volumes:
  zookeeper-01-data:
  kafka-broker-01-data:

networks:
  kafka-network:
    driver: bridge