server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: analytics-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3308}/${DB_NAME:qr-food-ordering_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Hop2005@}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 6000

  openapi:
    service:
      api-docs: qr-food-ordering-server
      server: http://localhost:8080,http://api.scanmeally.io
      title: API Service
      version: 1.0.0
