server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: notification-service


  openapi:
    service:
      api-docs: qr-food-ordering-server
      server: http://localhost:8080,http://api.scanmeally.io
      title: API Service
      version: 1.0.0
